version: '3.9'

services:
  users-service:
    build:
      context: ../../launcher-quarkus
      dockerfile: docker/Dockerfile.native
    container_name: users-service
    image: users-service:latest
    env_file:
      - ../../.env/local.service.env
    ports:
      - 8080:8080
    networks:
      - users-network
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    env_file:
      - ../../.env/local.db.env
    ports:
      - 27017:27017
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - users-network

networks:
  users-network:
    driver: bridge