apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-users-app-deployment
spec:
  selector:
    matchLabels:
      app: sample-users-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-users-app
    spec:
      containers:
      - name: sample-users
        image: users-service:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: sample-users-app-config
        imagePullPolicy: Never