quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      max-size: 8
      min-size: 2
      url: jdbc:postgresql://localhost:5432/postgres
    password: admin
    username: postgres
  hibernate-orm:
    database:
      generation: drop-and-create