apiVersion: v1
kind: ConfigMap
metadata:
  name: gsandwich-sandwiches-db-config
  labels:
    app: gsandwich-sandwiches-db
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin