kind: PersistentVolume
apiVersion: v1
metadata:
  name: gsandwich-sandwiches-db-pv
  labels:
    type: local
    app: gsandwich-sandwiches-db
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gsandwich-sandwiches-db-pv-claim
  labels:
    app: gsandwich-sandwiches-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi