spring:
  datasource:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    show-sql: false
  liquibase:
    enabled: false