version: '3.8'

services:

  sample-app:
    image: sample-app
    ports:
      - '8080:8080'
    environment:
      LOG_DIR: /tmp/logs

  sample-db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin