apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-config
  labels:
    app: sample-app
data:
  DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: admin
