apiVersion: v1
kind: Service
metadata:
  name: gsandwich-sandwiches-service
spec:
  # Make the service externally visible via the node
  type: NodePort
  ports:
  - name: http
    # Which port on the node is the service available through?
    nodePort: 30050
    # Inside the cluster, what port does the service expose?
    port: 8085
    # Which port do pods selected by this service expose?
    targetPort: 8080
    protocol: TCP
  selector:
    app: gsandwich-sandwiches